services:
  moorescnrwebsite:
    image: ${DOCKER_REGISTRY-}moorescnrwebsite
    build:
      context: .
      dockerfile: MoorescnrWebsite/Dockerfile
  moorescnrwebsite_mysql:
    image:   mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: