// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoorescnrWebsite.Database;

#nullable disable

namespace MoorescnrWebsite.Migrations
{
    [DbContext(typeof(CnrDbContext))]
    [Migration("20250417024846_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MoorescnrWebsite.Database.GunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<short>("ManufacturedYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("SalePrice")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasDatabaseName("idx_guns_description");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_guns_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("idx_guns_name");

                    b.HasIndex("Price")
                        .HasDatabaseName("idx_guns_price");

                    b.HasIndex("SalePrice")
                        .HasDatabaseName("idx_guns_saleprice");

                    b.ToTable("Guns");
                });

            modelBuilder.Entity("MoorescnrWebsite.Database.ImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("GunId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasComment("The order which the pictures are displayed");

                    b.HasKey("Id");

                    b.HasIndex("GunId")
                        .HasDatabaseName("idx_images_gunid");

                    b.HasIndex("Id")
                        .HasDatabaseName("idx_images_id");

                    b.ToTable("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
